# Generated by Django 4.1.3 on 2022-12-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, default='post_default.png', null=True, upload_to='posts/'),
        ),
    ]
